; PlatformIO Project Configuration File

[env]
platform = espressif32
framework = arduino
lib_deps =
    espressif/esp32-camera@^2.0.4
    WiFi @ ^2.0.0
    knolleary/PubSubClient @ ^2.8
monitor_speed = 115200

[env:esp32cam]
board = esp32cam
build_flags = -D CAMERA_MODEL_AI_THINKER
              -D MQTT_MAX_PACKET_SIZE=65000
