// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/ocr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OCRRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image data as bytes (PNG, JPEG, etc.)
	ImageData     []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRRequest) Reset() {
	*x = OCRRequest{}
	mi := &file_proto_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRRequest) ProtoMessage() {}

func (x *OCRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRRequest.ProtoReflect.Descriptor instead.
func (*OCRRequest) Descriptor() ([]byte, []int) {
	return file_proto_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *OCRRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type OCRResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extracted text from the image
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Error message if extraction failed
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Processing time in milliseconds
	ProcessingTimeMs int64 `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OCRResponse) Reset() {
	*x = OCRResponse{}
	mi := &file_proto_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRResponse) ProtoMessage() {}

func (x *OCRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRResponse.ProtoReflect.Descriptor instead.
func (*OCRResponse) Descriptor() ([]byte, []int) {
	return file_proto_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *OCRResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OCRResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OCRResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_proto_ocr_proto protoreflect.FileDescriptor

const file_proto_ocr_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/ocr.proto\x12\x03ocr\"+\n" +
	"\n" +
	"OCRRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"e\n" +
	"\vOCRResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x03R\x10processingTimeMs2>\n" +
	"\n" +
	"OCRService\x120\n" +
	"\vExtractText\x12\x0f.ocr.OCRRequest\x1a\x10.ocr.OCRResponseB\x13Z\x11ocr-service/protob\x06proto3"

var (
	file_proto_ocr_proto_rawDescOnce sync.Once
	file_proto_ocr_proto_rawDescData []byte
)

func file_proto_ocr_proto_rawDescGZIP() []byte {
	file_proto_ocr_proto_rawDescOnce.Do(func() {
		file_proto_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ocr_proto_rawDesc), len(file_proto_ocr_proto_rawDesc)))
	})
	return file_proto_ocr_proto_rawDescData
}

var file_proto_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ocr_proto_goTypes = []any{
	(*OCRRequest)(nil),  // 0: ocr.OCRRequest
	(*OCRResponse)(nil), // 1: ocr.OCRResponse
}
var file_proto_ocr_proto_depIdxs = []int32{
	0, // 0: ocr.OCRService.ExtractText:input_type -> ocr.OCRRequest
	1, // 1: ocr.OCRService.ExtractText:output_type -> ocr.OCRResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ocr_proto_init() }
func file_proto_ocr_proto_init() {
	if File_proto_ocr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ocr_proto_rawDesc), len(file_proto_ocr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ocr_proto_goTypes,
		DependencyIndexes: file_proto_ocr_proto_depIdxs,
		MessageInfos:      file_proto_ocr_proto_msgTypes,
	}.Build()
	File_proto_ocr_proto = out.File
	file_proto_ocr_proto_goTypes = nil
	file_proto_ocr_proto_depIdxs = nil
}
