#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
README_FILE="${ROOT_DIR}/README.md"
START_MARKER="<!-- SBOM:START -->"
END_MARKER="<!-- SBOM:END -->"
CYCLEDX_VERSION="v1.9.0"
GO_IMAGE="golang:1.25-bookworm"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

require_command() {
  local name="$1"
  if ! command -v "${name}" >/dev/null 2>&1; then
    echo "Missing required command: ${name}" >&2
    exit 1
  fi
}

require_command python3

if ! command -v go >/dev/null 2>&1 && ! command -v docker >/dev/null 2>&1; then
  echo "Missing required command: go or docker" >&2
  exit 1
fi

build_sbom() {
  local service_dir="$1"
  local output_file="$2"

  if command -v go >/dev/null 2>&1; then
    (
      cd "${service_dir}"
      go run github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@${CYCLEDX_VERSION} mod -licenses -json -output "${output_file}"
    )
    return
  fi

  docker run --rm \
    -v "${ROOT_DIR}:/repo" \
    -w "/repo/${service_dir#${ROOT_DIR}/}" \
    "${GO_IMAGE}" \
    sh -c "go run github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@${CYCLEDX_VERSION} mod -licenses -json -output /repo/${output_file#${ROOT_DIR}/}"
}

write_table() {
  local title="$1"
  local source_path="$2"
  local sbom_file="$3"
  local table_file="$4"
  local count

  python3 - "${sbom_file}" > "${table_file}" <<'PY'
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as handle:
  data = json.load(handle)

components = data.get("components") or []
rows = []
for component in components:
  if component.get("type") != "library":
    continue
  rows.append((component.get("name", "-"), component.get("version") or "-"))

for name, version in sorted(rows):
  print(f"{name}\t{version}")
PY
  count="$(grep -c '.' "${table_file}" || true)"

  {
    echo "### ${title}"
    echo
    echo "Source: ${source_path}"
    echo
    echo "CycloneDX file: ${sbom_file#${ROOT_DIR}/}"
    echo
    echo "Total dependencies: ${count}"
    echo
    echo "| Dependency | Version |"
    echo "|---|---|"
    if [[ "${count}" -eq 0 ]]; then
      echo "| (none) | - |"
    else
      awk -F'\t' '{printf "| %s | %s |\n", $1, $2}' "${table_file}"
    fi
    echo
  } >> "${TMP_DIR}/section.md"
}

SERVER_SBOM="${ROOT_DIR}/web/server/sbom.cdx.json"
OCR_SBOM="${ROOT_DIR}/web/ocr-service/sbom.cdx.json"
SERVER_TABLE="${TMP_DIR}/server.tsv"
OCR_TABLE="${TMP_DIR}/ocr.tsv"
SECTION_FILE="${TMP_DIR}/section.md"
README_TMP="${TMP_DIR}/README.md"

build_sbom "${ROOT_DIR}/web/server" "${SERVER_SBOM}"
build_sbom "${ROOT_DIR}/web/ocr-service" "${OCR_SBOM}"

{
  echo "${START_MARKER}"
  echo "## SBOM Snapshot"
  echo
  echo "This section is auto-generated by GitHub Actions from CycloneDX SBOM files."
  echo
  echo "Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo
} > "${SECTION_FILE}"

write_table "Go Backend Server" "web/server/go.mod" "${SERVER_SBOM}" "${SERVER_TABLE}"
write_table "OCR Service" "web/ocr-service/go.mod" "${OCR_SBOM}" "${OCR_TABLE}"

echo "${END_MARKER}" >> "${SECTION_FILE}"

if grep -q "${START_MARKER}" "${README_FILE}" && grep -q "${END_MARKER}" "${README_FILE}"; then
  awk -v start="${START_MARKER}" -v end="${END_MARKER}" -v repl="${SECTION_FILE}" '
    BEGIN {
      while ((getline line < repl) > 0) {
        block = block line "\n"
      }
      close(repl)
      in_block = 0
      replaced = 0
    }
    $0 == start {
      if (!replaced) {
        printf "%s", block
        replaced = 1
      }
      in_block = 1
      next
    }
    $0 == end {
      in_block = 0
      next
    }
    !in_block {
      print
    }
    END {
      if (!replaced) {
        printf "\n%s", block
      }
    }
  ' "${README_FILE}" > "${README_TMP}"
else
  cat "${README_FILE}" > "${README_TMP}"
  echo >> "${README_TMP}"
  cat "${SECTION_FILE}" >> "${README_TMP}"
fi

mv "${README_TMP}" "${README_FILE}"

echo "Updated ${README_FILE}, ${SERVER_SBOM}, and ${OCR_SBOM}"
