allow_anonymous true
 
# MQTT securizat cu mTLS
listener 8883
cafile /run/secrets/ca.crt
certfile /run/secrets/server.crt
keyfile /run/secrets/server.key
require_certificate true
use_subject_as_username true
allow_anonymous true
 
# Securitate si Limite (DoS Prevention)
# Limita dimensiune pachet (ex: 10MB)
message_size_limit 10485760
# Limita conexiuni simultane
max_connections 100
# Limita mesaje in asteptare (QoS 1/2) per client
max_inflight_messages 20
max_queued_messages 100

# Logare
log_type all
connection_messages true
log_timestamp true
