name: "Tests & Coverage"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: go.sum

      - name: Download dependencies
        working-directory: ./web/server
        run: go mod download

      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y libleptonica-dev libtesseract-dev tesseract-ocr


      - name: Install Mockgen
        run: |
          go install go.uber.org/mock/mockgen@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate Mocks
        working-directory: ./web/server
        run: |
          mkdir -p mocks

          mockgen \
            -package=mock_domain \
            -destination=mocks/user_mock.go \
            mqtt-streaming-server/domain UserRepository

          mockgen \
            -package=mock_domain \
            -destination=mocks/photo_mock.go \
            mqtt-streaming-server/domain PhotoRepository

          mockgen \
            -package=mock_domain \
            -destination=mocks/device_mock.go \
            mqtt-streaming-server/domain DeviceRepository
      - name: Run Tests and Coverage
        working-directory: ./web/server
        run: |
          go test -covermode=atomic -coverprofile=coverage.out ./...
          grep -v 'mocks/' coverage.out > coverage_clean.out
          go tool cover -func=coverage_clean.out
          go tool cover -func=coverage_clean.out | grep total

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage
          path: coverage_clean.out
          retention-days: 7