services:
  # Go API Service
  go-api:
    build: ./server
    user: "${UID}:${GID}"
    container_name: go-api
    image: server
    env_file: .env
    environment:
      - MQTT_HOST_IP=broker
    depends_on:
      - mongo-db
      - broker
    ports:
      - 8080:8080
    volumes:
      - ./uploads:/app/uploads
    networks:
      - backend
    secrets:
      - ca.crt
      - web.crt
      - web.key

  client:
    image: node:22-alpine
    user: "${UID}:${GID}"
    container_name: client
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn install && yarn dev:poll --host 0.0.0.0 --port 5173"
    networks:
      - backend
    depends_on:
      - go-api

  broker:
    user: "${UID}:${GID}"
    image: eclipse-mosquitto:latest
    container_name: broker
    hostname: broker
    ports:
      - "8883:8883"
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - backend
    secrets:
      - ca.crt
      - server.crt
      - server.key

  mongo-db:
    container_name: mongo-db
    hostname: mongo-db
    image: mongo:latest
    env_file: .env
    command: ["--auth"]
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:

secrets:
  ca.crt:
    file: ./secrets/ca.crt
  web.crt:
    file: ./secrets/web.crt
  web.key:
    file: ./secrets/web.key
  server.crt:
    file: ./secrets/server.crt
  server.key:
    file: ./secrets/server.key
